### PR TITLE
Added support for Ignoring certain groups from the UI

### PR DESCRIPTION
**Pull request by igerslike**
This pull request brings a feature to ignore certain translation keys from the Nova user interface, making it clear and also at same time, making sure the end-user does not translation unecessary keys.

### CODE REVIEW

**Comment by igerslike** [comment]
Im not sure if this should be included in the Chained Translation Manager package instead of this one, both would have their pros and cons. But makes more sense to me to clear up some "trash" from the dropdown.

**Comment by igerslike** [comment]
Oh there is missing to update the stub  config.php file.

**Comment by sten** [comment]
@igerslike Thanks a lot for your work! It is great to work on this together. I will test it tomorrow!

**Review by sten — APPROVED** [review]
Looks good! Thanks for your contribution! 

In the future, we are planning to add laravel guards to support authorisation access per translation group. This would be an additional level on top of your `ignore_groups` feature.

**Comment by sten** [comment]
@igerslike It is released! v1.2.1

**Pull request merged**
