### PR TITLE
Nova 4 and Vue3 Support

### PR DESCRIPTION
**Pull request by nelumoraru**

### CODE REVIEW

**Comment by sten** [comment]
@FrittenKeeZ & @nelumoraru Thanks for the work! I will review it tonight. But now we have 2 pull requests. Which is the preferred one. I assume the last one? Are there feature differences? Some more info, would make the review work faster ;-). Thanks a lot!

**Comment by nelumoraru** [comment]
I have now looked at the other pull request and they are pretty much the same, the only difference is i guess that tailwind in my pull request is scoped to the package and doesn't interfere with the rest of Nova.

**Comment by sten** [comment]
@nelumoraru Thanks for the swift feedback! I will review your pull request then.

**Comment by nelumoraru** [comment]
> @nelumoraru Thanks for the swift feedback! I will review your pull request then.

Awesome)

**Comment by FrittenKeeZ** [comment]
@sten I added some core cleanup as well in my PR, but I didn't touch any styling.
I'd say look through this PR first and merge it, then I'll update mine in regards to merge conflicts and you can review the last fixes.

**Comment by FrittenKeeZ** [comment]
@sten I just resolved the merge conflicts in my PR

**Comment by sten** [comment]
Great work, @nelumoraru ! I will merge the PR and fix the small remark myself.

**Pull request merged**
